In [1]:
!pip install sklearn

In [2]:
## Libraries

import pandas as pd
import numpy as np
import os
import sklearn
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [3]:
path = 'D:\EDA\Workspace'
os.chdir(path)

car = pd.read_excel('Cars.xlsx')
car.head(2)

manufacturer model  displ  year  cyl       trans  cty  hwy fl    class
0         audi    a4    1.8  1999    4    auto(l5)   18   29  p  compact
1         audi    a4    1.8  1999    4  manual(m5)   21   29  p  compact

In [6]:
## SLR - Simple Linear Regression

# Defining x and y
x = car[['cty']]
y = car[['hwy']]

# Create a blank linear Regression object and name it
lm = LinearRegression()

# Fitting the model or acturally creating model (y = ax + b)
model = lm.fit(x,y)

# Printing the value for intercept value (b value)
print("Intercept value : ", lm.intercept_)

# Printing the value for coefficient value (a value)
print("Coefficient value : ", lm.coef_)

Intercept value :  [0.8920411]
Coefficient value :  [[1.33745561]]


In [8]:
## Predict the highway milage from city milage

# Create a validation data set
val_data = pd.DataFrame.from_dict({'cty': [26] })
val_data

pred_highway_milage = model.predict(val_data)
pred_highway_milage

array([[35.66588697]])

## Estimate how many drinks would be sold if one day there were 50 visitors

In [9]:
drink = pd.read_excel('Drinks.xlsx')
drink.head(2)

Day  Number of Visitors  Drinks sold
0   Monday                  32           17
1  Tuesday                  45           20

In [14]:
x = drink[['Number of Visitors']]
y = drink[['Drinks sold']]

lm = LinearRegression()

model = lm.fit(x,y)
print(lm.coef_)
print(lm.intercept_)

[[0.68129262]]
[-10.19329973]


In [12]:
val_data = pd.DataFrame.from_dict({'Number of Visitors': [50] })
val_data

Number of Visitors
0                  50

In [13]:
pred_drink_sold = model.predict(val_data)
pred_drink_sold

array([[23.87133116]])

## 4 step process of build model

In [16]:
x = car[['cty']]
y = car[['hwy']]

## Step-1 : Splitting the data into training and test

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2) # or train_size = 0.8
len(x_train), len(x_test), len(y_train), len(y_test)

(187, 47, 187, 47)

In [17]:
x_train.head()

cty
124   15
193   24
14    15
176   15
73    11

In [18]:
## Step-2 : Creating the model

lm = LinearRegression()
model = lm.fit(x_train, y_train)

lm.coef_ , lm.intercept_

(array([[1.3289008]]), array([1.02682174]))

In [20]:
print(x_test.head(2)) 
print(y_test.head(2))

     cty
115   19
82    13
     hwy
115   26
82    17


In [23]:
## Step-3 : predict the result for x_test

y_test['hwy_pred'] = model.predict(x_test)

round(y_test,2).head(10)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


hwy  hwy_pred
115   26     26.28
82    17     18.30
56    15     15.64
213   29     28.93
25    26     22.29
70    15     15.64
161   27     27.60
141   29     28.93
10    27     26.28
74    17     15.64

In [27]:
y_test['hwy'].mean(), y_test['hwy_pred'].mean()

(23.21276595744681, 23.1657436047688)

In [28]:
y_test.corr()

hwy  hwy_pred
hwy       1.000000  0.968426
hwy_pred  0.968426  1.000000

In [29]:
## Step-4 : Predict the value

val_data = pd.DataFrame.from_dict({'cty': [26] })

model.predict(val_data)

array([[35.57824258]])